[build]
  command   = "npm install --legacy-peer-deps --workspace=client && npm run build --workspace=client"
  publish   = "client/dist"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
